name=input("Enter your name:")
br=input("Enter your branch:")
gend=input("Enter your gender:")
cog=input("Enter your college name:")
age=input("Enter your age:")
print(name)
print(br)
print(gend)
print(cog)
print(age)